// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_cicyFbUXIv-9kmSxpkadVm3P5FMqpfE',
    appId: '1:79107251002:web:c144c364b1d1b0f8cd4e03',
    messagingSenderId: '79107251002',
    projectId: 'pythonlearningapp-b0edb',
    authDomain: 'pythonlearningapp-b0edb.firebaseapp.com',
    storageBucket: 'pythonlearningapp-b0edb.firebasestorage.app',
    measurementId: 'G-CVT69WDVN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhf8FyEGFBs5hKe0UUVqg6c8RF725L7RE',
    appId: '1:79107251002:android:11ce9854b2318d75cd4e03',
    messagingSenderId: '79107251002',
    projectId: 'pythonlearningapp-b0edb',
    storageBucket: 'pythonlearningapp-b0edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQfuZY6ZfajJJ8wtG5nlPLT0ErSme_ww',
    appId: '1:79107251002:ios:ef32848186c5bf29cd4e03',
    messagingSenderId: '79107251002',
    projectId: 'pythonlearningapp-b0edb',
    storageBucket: 'pythonlearningapp-b0edb.firebasestorage.app',
    iosBundleId: 'com.example.apcsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWQfuZY6ZfajJJ8wtG5nlPLT0ErSme_ww',
    appId: '1:79107251002:ios:ef32848186c5bf29cd4e03',
    messagingSenderId: '79107251002',
    projectId: 'pythonlearningapp-b0edb',
    storageBucket: 'pythonlearningapp-b0edb.firebasestorage.app',
    iosBundleId: 'com.example.apcsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_cicyFbUXIv-9kmSxpkadVm3P5FMqpfE',
    appId: '1:79107251002:web:00f320a001fca5f5cd4e03',
    messagingSenderId: '79107251002',
    projectId: 'pythonlearningapp-b0edb',
    authDomain: 'pythonlearningapp-b0edb.firebaseapp.com',
    storageBucket: 'pythonlearningapp-b0edb.firebasestorage.app',
    measurementId: 'G-XFQ5QSDQRT',
  );
}
